import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
// import navbar from "../components/navbar";
export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          .imgF {
            position: absolute;
            left: 49%;
            color: blue;
          }
        `}
      </style>
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
      <hgroup className={styles.hGroup}>
        <h1>Welcome to Codes</h1>
        <p>
          Here You will find everything about coding
        </p>
        </hgroup>
        <div className="img1">
        <Image
          src="/../public/Images/2.jpeg"
          alt="cap"
          width="500"
          height="450"
        />
       
        </div>

        <div className="blogs">
          <h1>Popular Blogs</h1>
          <div className="blogItem">
      <h2>This is the title of the blog</h2>
      <p className={styles.first}>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi,
        nulla quod. Neque atque odio est debitis alias pariatur, voluptatem
        officiis quod vel cum ullam
        </p>
        <hr />
    </div>
        </div>
      </main>
      <br />
      <footer className={styles.footer}>
      {/* <p className="imgF">HELLO</p> */}
        <p>Powered by Suraj Dhankad</p>
      </footer>
    </div>
  );
}
